version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: hiretrack_application
    environment:
      - POSTGRES_USER=nitin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hiretrack_apps_db
    ports:
      - "127.0.0.1:5434:5432"
    volumes:

      - postgres_data:/var/lib/postgresql 

volumes:
  postgres_data: