version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: hiretrack_auth
    environment:
      - POSTGRES_USER=nitin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hiretrack_auth_db
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      # FIX: Mount to the root postgresql folder, not /data
      - postgres_data:/var/lib/postgresql 

volumes:
  postgres_data: